<a href="https://colab.research.google.com/github/invoker-qqwrv/Beida_tensorflow/blob/main/1_3creat_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
# tf.constant(tensor的内容，dtype=数据类型)
a=tf.constant([1,5],dtype=tf.int64)
#以上是一阶tensor,内容是1和5，int型
print(a)


tf.Tensor([1 5], shape=(2,), dtype=int64)


In [3]:
print(a.dtype)
print(a.shape)#逗号隔开几个数字，tensor就是几维的，这里逗号隔开了一个数字，说明tensor是一维的。2表示tensor里面有两个元素，也就是1,5

<dtype: 'int64'>
(2,)


In [5]:
#很多时候数据由numpy格式给出。可以转换成tensor格式
# tf.convert_to_tensor（数据名,dtype=数据类型）
import numpy as np
a=np.arange(0,5)
# 用于生成数组numpy.arange(start, stop, step, dtype = None)
b=tf.convert_to_tensor(a,dtype=tf.int64)
print(a)
print(b)

[0 1 2 3 4]
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int64)


In [6]:
a=tf.zeros([2,3])#两行三列的全0tensor
print(a)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [7]:
b=tf.ones(2)#1 row 2columns all 1
c=tf.fill([2,3],9)#two rows and three columns with all 9
print(b)
print(c)

tf.Tensor([1. 1.], shape=(2,), dtype=float32)
tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)


In [11]:
# Generate normally distributed random numbers
# tf.random.normal(dimension,mean=mean value,stddev=standard )
# 截断正态分布(Truncated_normal_distribution) 是在正态分布中界定随机变量进而从正态分布的分布函数中导出概率分布，在计量经济学中具有广泛的应用。
# tf.random.truncated_normal(dimension,mean=mean value,stddev=standard)
#可以保证均值在正负两倍标准差之内μ±2sigma
print(tf.random.normal([2,3],mean=0.5,stddev=1))#2row 3column 
print(tf.random.truncated_normal([2,3],mean=0.5,stddev=1))#数据都在两倍标准差之内，取值更靠近mean value


tf.Tensor(
[[-0.6542336  -1.5736508   0.04745087]
 [-0.23727793  2.2229      0.38104782]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.03879252  0.08024842  1.2683885 ]
 [ 0.8284681   1.3503892  -0.01950908]], shape=(2, 3), dtype=float32)


In [14]:
# Evenly distributed均匀分布
# tf.random.uniform(dimension,minval=minvalue,maxval=maxvalue)前闭后开区间
print(tf.random.uniform([2,3],minval=0,maxval=1.1))

tf.Tensor(
[[0.4873839  0.4671206  0.83308315]
 [1.0305551  0.5744416  0.7120046 ]], shape=(2, 3), dtype=float32)
