<a href="https://colab.research.google.com/github/invoker-qqwrv/Beida_tensorflow/blob/main/1_4Common_functions_and_Arithmetic_of_tf.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 强制tensor转换为该数据类型
tf.cast(tensor名，dtype=)


In [ ]:
# 计算tensor维度上的最小值
tf.reduce_min(tensor名)
# 计算tensor维度上的最大值
tf.reduce_max(tensor名)

In [10]:
import tensorflow as tf
a=tf.constant([1,2,3,4],dtype=tf.float32)
print(a)
b=tf.cast(a,tf.int32)
print(b)
print(tf.reduce_max(b))
print(tf.reduce_min(b))

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
#axis=0 column       
#axis=1 row
#计算tensor沿着指定维度的均值
# tf.reduce_mean(tensor名，axis=)
# tf.reduce_sum(tensor,axis=)

In [11]:
x=tf.constant([[1,2,3],[4,5,6]])
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [14]:
print(tf.reduce_sum(x,axis=0))
print(tf.reduce_mean(x))
print(tf.reduce_mean(x,axis=0))

tf.Tensor([5 7 9], shape=(3,), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [16]:
# tf.Variable()将变量标记为可训练，被标记的变量会在反向传播中记录梯度信息。
# tf.Variable(初始值)
w=tf.Variable(tf.random.normal([2,2],mean=0,stddev=1))
print(w)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.292916  , -1.063325  ],
       [ 0.1881849 , -0.21629612]], dtype=float32)>


In [18]:
# tf常用数学运算
# tf.add(tensor1,tensor2)
# tf.substract(tensor1,tensor2)
# tf.multiply(tensor1,tensor2)
# tf.divide(tensor1,tensor2)
# tf.square(tensor名)平方
# tf.pow(tensor名，次方数)n次方
# tf.sqrt(tensor名)计算tensor的开方
# tf.matmul(矩阵1，矩阵2)

In [22]:

# 神经网络在训练时一定是把输入特征和标签一起送进网络的
# data=tf.data.Dataset.from_tensor_slices((输入特征，标签))
# 这个可以传入tensor的第一维度，生成输入特征/标签对。构建数据集
# 这个就是特征和标签配对的函数。
features=tf.constant([12,34,54,6,6])
labels=tf.constant([0,1,1,1,0])
dataset=tf.data.Dataset.from_tensor_slices((features,labels))#注意这里是双括号
print(dataset)
for element in dataset:
  print(element)

<TensorSliceDataset element_spec=(TensorSpec(shape=(), dtype=tf.int32, name=None), TensorSpec(shape=(), dtype=tf.int32, name=None))>
(<tf.Tensor: shape=(), dtype=int32, numpy=12>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
(<tf.Tensor: shape=(), dtype=int32, numpy=34>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=54>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=6>, <tf.Tensor: shape=(), dtype=int32, numpy=1>)
(<tf.Tensor: shape=(), dtype=int32, numpy=6>, <tf.Tensor: shape=(), dtype=int32, numpy=0>)
