<a href="https://colab.research.google.com/github/invoker-qqwrv/Beida_tensorflow/blob/main/1_5commonly_used_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# tf.GradientTape()
# with---
# enumerate()
# assign_sub()
# tf.one_hot()
# tf.nn.softmax()
#tf,argmax

In [2]:
import tensorflow as tf
# tf.GradientTape 
# structure:
# with记录计算过程，gradient求出tensor's dimension
# with tf.GradientTape() as tape:
#   若干过程
# grad=tape.gradient(函数，对谁求导)
with tf.GradientTape() as tape:
  w=tf.Variable(tf.constant(3.0))
  loss=tf.pow(w,2)
grad=tape.gradient(loss,w)
print(grad)

tf.Tensor(6.0, shape=(), dtype=float32)


In [4]:
# enumerate函数
a=['aaa','bbb','ccc']
for i,element in enumerate(a):
  print(i,element)#i 和element配对

0 aaa
1 bbb
2 ccc


In [5]:
# tf.one_hot在分类问题中用这个表示标签、可以将带转换数据转换为one hot形式输出
# tf.one_hot(等待转换数据，depth=几分类)
# 1表示是。0表示非
classes=3#三分类
labels=tf.constant([1,0,2])#输入函数最小值为0最大值为2
#输出为onehot形式
output=tf.one_hot(labels,depth=classes)
print(output)
#按row来算，第一行是第一个数为1，第二行第0个数为1-------

tf.Tensor(
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [8]:
# 对于分类问题，神经网络前向传播后，得到每一个分类的可能性。
# 这些输出只有符合概率分布才能于onehot label做对比
# 此时可用tf.nn.softmax()使输出符合概率分布。
y=tf.constant([1.01,2.01,-0.66])#第一次的357报错可能是输入的数不行。这个也是由要求的
y_pro=tf.nn.softmax(y)
print(y_pro)


tf.Tensor([0.25598174 0.69583046 0.04818781], shape=(3,), dtype=float32)


In [9]:
# assign_sub函数
# 赋值操作，更新参数值并且返回
# 调用该函数前，先用tf.Variable定义变量为可训练（可自更新）
# w.assign_sub(w要自减的内容)
w=tf.Variable(4)
w.assign_sub(1)#w=w-1
print(w)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>


In [ ]:
#tf,argmax返回