<a href="https://colab.research.google.com/github/invoker-qqwrv/Beida_tensorflow/blob/main/2_1basic_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# tf.where(条件语句，真返回a，假返回b)
import tensorflow as tf
a=tf.constant([1,2,3,4,5])
b=tf.constant([4,5,2,4,1])
c=tf.where(tf.greater(a,b),a,b)
print(c)


tf.Tensor([4 5 3 4 5], shape=(5,), dtype=int32)


In [4]:
#np.random.RandomState.rand(dimension)返回一个[0，1)之间的随机数
# 维度为空，返回一个标量
import numpy as np
rdm=np.random.RandomState(seed=1)#seed为常数，每次生成随机数相同
a=rdm.rand()#返回随机标量
b=rdm.rand(2,3)#返回维度为两行三列随机数矩阵
print(a)
print(b)

0.417022004702574
[[7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01]]


In [8]:
# np.vstack(数组1，数组2）将两个数组按垂直方向叠加
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.vstack((a,b))#注意这里有两个括号
print(c)
# 变成了2维数组

[[1 2 3]
 [4 5 6]]


In [9]:
# np.mgrid[起始值：结束值：步长]多组可以接着写，中间用，隔开.每一组是一个维度。
# 第一组表示竖着的，第二组表示横向的
# 第一组决定有多少行，第二组决定有多少列
x,y=np.mgrid[1:3:1,2:4:0.5]
print(x)
print(y)
# x.ravel()将x变为一维数组


[[1. 1. 1. 1.]
 [2. 2. 2. 2.]]
[[2.  2.5 3.  3.5]
 [2.  2.5 3.  3.5]]


In [10]:
# np.c_[]使返回的间隔数值点配对
# x.ravel()将x变为一维数组。
grid=np.c_[x.ravel(), y.ravel()]
print(grid)

[[1.  2. ]
 [1.  2.5]
 [1.  3. ]
 [1.  3.5]
 [2.  2. ]
 [2.  2.5]
 [2.  3. ]
 [2.  3.5]]
