<a href="https://colab.research.google.com/github/invoker-qqwrv/Beida_tensorflow/blob/main/2_4loss_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 损失函数就是预测值y与标准值y_之间的差距。
# mse：loss_mse=tf.reduce_mean(tf.square(y,y_))


In [12]:
# x1和x2是影响日销量的因素。销量是y_。噪声-0.05-0.05
# 这里用了mes，是默认了销量预测多了和少了，损失是一样的
# 接下来构建一层的神经网络
import tensorflow as tf
import numpy as np
SEED=23455
rdm=np.random.RandomState(seed=SEED)  #生成[0,1)之间的随机数
x=rdm.rand(32,2)#生成32行两列的随机数，也就是x1和x2
y_=[[x1+x2+(rdm.rand()/10.0-0.05)] for (x1,x2) in x]  # .rand函数生成噪声[0,1)/10=[0,0.1);[0,0.1)-0.05=[-0.05,0.05)
x=tf.cast(x, dtype=tf.float32)
w1=tf.Variable(tf.random.normal([2,1], stddev=1,seed=1))#随机初始化w1
epoch=15000
lr=0.002
for epoch in range(epoch):
  with tf.GradientTape() as tape:
    y=tf.matmul(x,w1)#前向传播计算结果
    loss_mse=tf.reduce_mean(tf.square(y_-y))#损失函数均方误差
  grads=tape.gradient(loss_mse,w1)
  w1.assign_sub(lr*grads)
  if epoch%500==0:
    print("After %d training steps,w1 is"%(epoch))
    print(w1.numpy(),"\n")
print("Final w1 is:",w1.numpy())

After 0 training steps,w1 is
[[-0.7648834]
 [-0.4465386]] 

After 500 training steps,w1 is
[[0.27169284]
 [0.63153684]] 

After 1000 training steps,w1 is
[[0.64486957]
 [0.97207904]] 

After 1500 training steps,w1 is
[[0.79063535]
 [1.0686706 ]] 

After 2000 training steps,w1 is
[[0.85631734]
 [1.0864854 ]] 

After 2500 training steps,w1 is
[[0.8920836]
 [1.0804592]] 

After 3000 training steps,w1 is
[[0.91533583]
 [1.0685775 ]] 

After 3500 training steps,w1 is
[[0.9323635]
 [1.0565025]] 

After 4000 training steps,w1 is
[[0.94564295]
 [1.0458139 ]] 

After 4500 training steps,w1 is
[[0.9563044]
 [1.0367833]] 

After 5000 training steps,w1 is
[[0.9649721]
 [1.0292872]] 

After 5500 training steps,w1 is
[[0.97205573]
 [1.0231088 ]] 

After 6000 training steps,w1 is
[[0.97785723]
 [1.018031  ]] 

After 6500 training steps,w1 is
[[0.982613 ]
 [1.0138624]] 

After 7000 training steps,w1 is
[[0.986513 ]
 [1.0104423]] 

After 7500 training steps,w1 is
[[0.98971164]
 [1.0076357 ]] 

After 80

In [16]:
# 如果也测多了，损失的是成本，预测少了，损失的是利润
# 如果利润不等于成本，那mes产生的loss无法实现利益最大化
# 此时使用自定义损失函数
# 这时假设成本1元，利润99
import tensorflow as tf
import numpy as np
SEED=23455
COST=1
PROFIT=99
rdm=np.random.RandomState(seed=SEED)  #生成[0,1)之间的随机数
x=rdm.rand(32,2)#生成32行两列的随机数，也就是x1和x2
y_=[[x1+x2+(rdm.rand()/10.0-0.05)] for (x1,x2) in x]  # .rand函数生成噪声[0,1)/10=[0,0.1);[0,0.1)-0.05=[-0.05,0.05)
x=tf.cast(x, dtype=tf.float32)
w1=tf.Variable(tf.random.normal([2,1], stddev=1,seed=1))#随机初始化w1
epoch=15000
lr=0.002
for epoch in range(epoch):
  with tf.GradientTape() as tape:
    y=tf.matmul(x,w1)#前向传播计算结果
    loss=tf.reduce_sum(tf.where(tf.greater(y,y_),(y-y_)*COST,(y_-y)*PROFIT))
    #预测的y<y_了会损失利润，大于了会损失成本（cost）
    # tf.greater(a,b)比较ab的大小，a大于b输出true反之输出false。
    # tf。where询问，y大于y_吗。如果成立，就输出第一个，如果不成立，输出第二个。最后对所有损失求和。
  grads=tape.gradient(loss,w1)
  w1.assign_sub(lr*grads)
  if epoch%500==0:
    print("After %d training steps,w1 is"%(epoch))
    print(w1.numpy(),"\n")
print("Final w1 is:",w1.numpy())

After 0 training steps,w1 is
[[3.0493035]
 [3.0913029]] 

After 500 training steps,w1 is
[[1.1228163]
 [1.0298307]] 

After 1000 training steps,w1 is
[[1.1131963]
 [1.0611144]] 

After 1500 training steps,w1 is
[[1.1035764]
 [1.0923984]] 

After 2000 training steps,w1 is
[[1.1525896]
 [1.1349752]] 

After 2500 training steps,w1 is
[[1.1429697]
 [1.1662592]] 

After 3000 training steps,w1 is
[[1.171165]
 [1.032366]] 

After 3500 training steps,w1 is
[[1.1615452]
 [1.06365  ]] 

After 4000 training steps,w1 is
[[1.1519252]
 [1.0949339]] 

After 4500 training steps,w1 is
[[1.1423051]
 [1.1262176]] 

After 5000 training steps,w1 is
[[1.1326848]
 [1.1575011]] 

After 5500 training steps,w1 is
[[1.16088  ]
 [1.0236079]] 

After 6000 training steps,w1 is
[[1.1512599]
 [1.0548916]] 

After 6500 training steps,w1 is
[[1.1416402]
 [1.0861757]] 

After 7000 training steps,w1 is
[[1.13202  ]
 [1.1174593]] 

After 7500 training steps,w1 is
[[1.1810334]
 [1.1600363]] 

After 8000 training steps,w1 i