<a href="https://colab.research.google.com/github/invoker-qqwrv/Beida_tensorflow/blob/main/2_4loss_function.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 损失函数就是预测值y与标准值y_之间的差距。
# mse：loss_mse=tf.reduce_mean(tf.square(y,y_))

In [7]:
# x1和x2是影响日销量的因素。销量是y_。噪声-0.05-0.05
# 接下来构建一层的神经网络
import tensorflow as tf
import numpy as np
SEED=23455
rdm=np.random.RandomState(seed=SEED)  #生成[0,1)之间的随机数
x=rdm.rand(32,2)#生成32行两列的随机数，也就是x1和x2
y_=[[x1+x2+(rdm.rand()/10.0-0.05)] for (x1,x2) in x]  # .rand函数生成噪声[0,1)/10=[0,0.1);[0,0.1)-0.05=[-0.05,0.05)
x=tf.cast(x, dtype=tf.float32)
w1=tf.Variable(tf.random.normal([2,1], stddev=1,seed=1))#随机初始化w1
epoch=15000
lr=0.002
for epoch in range(epoch):
  with tf.GradientTape() as tape:
    y=tf.matmul(x,w1)#前向传播计算结果
    loss_mse=tf.reduce_mean(tf.square(y_-y))#损失函数均方误差
  grads=tape.gradient(loss_mse,w1)
  w1.assign_sub(lr*grads)
  if epoch%500==0:
    print("After %d training steps,w1 is"%(epoch))
    print(w1.numpy(),"\n")
print("Final w1 is:",w1.numpy())

After 0 training steps,w1 is
[[-0.6630008 ]
 [-0.41332614]] 

After 500 training steps,w1 is
[[0.32583413]
 [0.6252373 ]] 

After 1000 training steps,w1 is
[[0.67938864]
 [0.95564044]] 

After 1500 training steps,w1 is
[[0.815626 ]
 [1.0513977]] 

After 2000 training steps,w1 is
[[0.8756989]
 [1.0710448]] 

After 2500 training steps,w1 is
[[0.9076067]
 [1.0673648]] 

After 3000 training steps,w1 is
[[0.9279425]
 [1.0576942]] 

After 3500 training steps,w1 is
[[0.94266135]
 [1.047527  ]] 

After 4000 training steps,w1 is
[[0.95407534]
 [1.0384357 ]] 

After 4500 training steps,w1 is
[[0.96321654]
 [1.0307256 ]] 

After 5000 training steps,w1 is
[[0.9706401]
 [1.0243163]] 

After 5500 training steps,w1 is
[[0.9767041]
 [1.0190308]] 

After 6000 training steps,w1 is
[[0.98166996]
 [1.0146861 ]] 

After 6500 training steps,w1 is
[[0.98574036]
 [1.0111187 ]] 

After 7000 training steps,w1 is
[[0.98907816]
 [1.0081911 ]] 

After 7500 training steps,w1 is
[[0.99181557]
 [1.0057896 ]] 

After 

In [ ]:
# 如果也测多了，损失的是成本，预测少了，损失的是利润
# 如果利润不等于成本，那mes产生的loss无法实现利益最大化